previewsEnabled: true
previewsExpireAfterDays: 7
services:
- type: web
  name: guestbook-go
  runtime: docker
  rootDir: guestbook-go
  envVars:
  - key: REDIS_PRIMARY_URL
    fromService:
      name: redis-primary
      type: pserv
      property: hostport
  - key: REDIS_REPLICA_URL
    fromService:
      name: redis-replica
      type: pserv
      property: hostport
- type: pserv
  name: redis-primary
  runtime: image
  image:
    url: renderco/k8s-redis:e2e
- type: pserv
  name: redis-replica
  runtime: image
  numInstances: 2
  image:
    url: renderco/k8s-redis-replica:v2
  envVars:
  - key: GET_HOSTS_FROM
    value: env
  - key: REDIS_MASTER_SERVICE_HOST
    fromService:
      name: redis-primary
      type: pserv
      property: host
